name: Test And Sync
on:
  push:

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        rust-toolchain: [nightly]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rust-src, clippy, rustfmt
        targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat
    - name: Clippy for the default target
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Check code format
      run: cargo fmt --all -- --check

  sync:
    needs: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        # Please set the private key in the repository settings
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Enable git-subrepo subcommands
      run: git clone https://github.com/ingydotnet/git-subrepo /tmp/git-subrepo 
        
    - name: Synchronize with remote terminal modules
      run: |
        source /tmp/git-subrepo/.rc
        source ./scripts/build/repo.sh
        CloneRepoConfig
        LoadRepoConfig
        UpdateRepoConfig